### ISSUE TITLE
streamlining checkCC

### ISSUE THREAD

**Issue by micahpf** [yerkes-gencore/gencoreSC#59]
The workflow for checking cc in the package is outdated and clunky. The following changes can streamline it a lot (and remove several problematic/gratuitous dependencies):
- [x] Break checkCC into two parts, `scoreCC()` and `checkPCA()`, run each with `lapply()` separately
- [x] ~~Remove the `%<-%` functionality. I like the concept but it's not really compatible with the `lapply()` workflow we've adopted~~ Moved to suggests. It's still useful with our SingleR wrapper.
- [x] ~~Use `NormFindVarFeatScaleData()` in `scoreCC()` to keep things concise and consistent.~~ Not possible. Fine to keep it as is.
- [x] Force the use to pass in s.score and g2m.score gene lists separately. Currently it requires a cc_genes names list with specific names (. seps rather than _) and errors with a uninformative message otherwise.
- [x] Remove `EnsDb2GeneName()` from package and move to template `R/` and/or vignettes as a convenience function. It requires AnnotationHub() and several bioc database packages that aren't used for the rest of the package and which introduce exotic namespace issues.
- [x] ~~Add the cc genes for mouse as built-in data? May be simpler to just use `scGate::genes.blacklist.default$Mm$cellCycle.G1S` since those are already used for blacklisting in PCA and integration anyway. Note that those lists are slightly different (more conservative?) than those derived from the hbctraining script I've been using previously.~~ Just put code for getting mouse data in the examples of scoreCC. We can put in a vignette or the template too.

**Comment by derrik-gratz** [comment]
Possibly address this as well? We could move it to `addQCmetrics` 

https://github.com/yerkes-gencore/gencoreSC/issues/16
