### ISSUE TITLE
NormFindVarFeatures having differing behavior than manual workflow when trying Harmony with WNN

### ISSUE THREAD

**Issue by derrik-gratz** [yerkes-gencore/gencoreSC#69]
I'm not exactly sure what or why is different, but the resulting Dim. Reduc. from running harmony after preprocessing RNA data with NormFind... is very messy, no clear relationship between the dim and the amount of variance explained (elbow plot has no trend). If I run the preprocessing manually, it seems to work as expected. Will have to see if this is repeatable with other datasets.

**Comment by micahpf** [comment]
Got a reproducible example I could try?

**Comment by derrik-gratz** [comment]
not really lol, but I documented it here in case we encounter the issue again. The dimplots looked very different with and without manual NFVF. I'll close this and we can re-open if I get better reproducibility
